import pygame
player1_idle_image = [pygame.image.load("image/player 1/idle/1.png").convert_alpha(),
                      pygame.image.load("image/player 1/idle/2.png").convert_alpha(),
                      pygame.image.load("image/player 1/idle/3.png").convert_alpha(),
                      pygame.image.load("image/player 1/idle/4.png").convert_alpha(),
                      pygame.image.load("image/player 1/idle/5.png").convert_alpha(),
                      pygame.image.load("image/player 1/idle/6.png").convert_alpha(),
                      pygame.image.load("image/player 1/idle/7.png").convert_alpha(),
                      pygame.image.load("image/player 1/idle/8.png").convert_alpha()]
player1_run_image = [pygame.image.load("image/player 1/run/1.png").convert_alpha(),
                     pygame.image.load("image/player 1/run/2.png").convert_alpha(),
                     pygame.image.load("image/player 1/run/3.png").convert_alpha(),
                     pygame.image.load("image/player 1/run/4.png").convert_alpha(),
                     pygame.image.load("image/player 1/run/5.png").convert_alpha(),
                     pygame.image.load("image/player 1/run/6.png").convert_alpha(),
                     pygame.image.load("image/player 1/run/7.png").convert_alpha(),
                     pygame.image.load("image/player 1/run/8.png").convert_alpha()]
player1_atk_image = [pygame.image.load("image/player 1/attack/1.png").convert_alpha(),
                     pygame.image.load("image/player 1/attack/2.png").convert_alpha(),
                     pygame.image.load("image/player 1/attack/3.png").convert_alpha(),
                     pygame.image.load("image/player 1/attack/4.png").convert_alpha(),
                     pygame.image.load("image/player 1/attack/5.png").convert_alpha(),
                     pygame.image.load("image/player 1/attack/6.png").convert_alpha(),
                     pygame.image.load("image/player 1/attack/7.png").convert_alpha(),
                     pygame.image.load("image/player 1/attack/8.png").convert_alpha(),
                     pygame.image.load("image/player 1/attack/9.png").convert_alpha(),
                     pygame.image.load("image/player 1/attack/10.png").convert_alpha(),
                     pygame.image.load("image/player 1/attack/11.png").convert_alpha()]
player2_idle_image = [pygame.image.load("image/1.png").convert_alpha(),
                      pygame.image.load("image/2.png").convert_alpha(),
                      pygame.image.load("image/3.png").convert_alpha(),
                      pygame.image.load("image/4.png").convert_alpha()]
player2_run_image = [pygame.image.load("image/player 2/run/1.png").convert_alpha(),
                     pygame.image.load("image/player 2/run/2.png").convert_alpha(),
                     pygame.image.load("image/player 2/run/3.png").convert_alpha(),
                     pygame.image.load("image/player 2/run/4.png").convert_alpha()]
player2_atk_image = [pygame.image.load("image/player 2/attack/1.png").convert_alpha(),
                     pygame.image.load("image/player 2/attack/2.png").convert_alpha(),
                     pygame.image.load("image/player 2/attack/3.png").convert_alpha(),
                     pygame.image.load("image/player 2/attack/4.png").convert_alpha(),
                     pygame.image.load("image/player 2/attack/5.png").convert_alpha(),
                     pygame.image.load("image/player 2/attack/6.png").convert_alpha(),
                     pygame.image.load("image/player 2/attack/7.png").convert_alpha(),
                     pygame.image.load("image/player 2/attack/8.png").convert_alpha(),
                     pygame.image.load("image/player 2/attack/9.png").convert_alpha(),
                     pygame.image.load("image/player 2/attack/10.png").convert_alpha(),
                     pygame.image.load("image/player 2/attack/11.png").convert_alpha(),
                     pygame.image.load("image/player 2/attack/12.png").convert_alpha()]
bg_image = [pygame.image.load("image/fon/1.jpg").convert_alpha(),
            pygame.image.load("image/fon/2.jpg").convert_alpha(),
            pygame.image.load("image/fon/3.jpg").convert_alpha(),
            pygame.image.load("image/fon/4.jpg").convert_alpha(),
            pygame.image.load("image/fon/5.jpg").convert_alpha(),
            pygame.image.load("image/fon/6.jpg").convert_alpha(),
            pygame.image.load("image/fon/7.jpg").convert_alpha(),
            pygame.image.load("image/fon/8.jpg").convert_alpha()]